# @package _global_

base_logs_home: /cluster/scratch/abizeul/mae_alice
base_data_home: /cluster/scratch/abizeul 

checkpoint_folders:
  vit-t:
    tinyimagenet:
      pixel:
        pixel:
          _50:
            _8:
          _60:
            _8: 
          _75:
            _8: 
          _80:
            _8: 
          _90: 
            _8: mae_tiny_pixel_0.9_lossA/2025-03-28_18-29-04
        sampling:
          _None: 
            _8: 
      pc:
        pc:
          _5:
            _8: 
          _10:
            _8: 
          _20:
            _8: pcmae_tiny_pc_pc_pc_0.2_lossA/2025-03-26_23-23-30
          _30:
            _8: 
          _40:
            _8: 
          _50:
            _8: 
        sampling_pc:
          _None: 
            _8: 
    cifar10: 
      pixel:
        pixel:
          _50:
            _8: 
          _60:
            _8: 
          _75:
            _8: 
            _16: 
          _80:
            _8: mae_cifar10_pixel_0.8_lossA/2025-03-28_15-42-32 #mae_cifar10_pixel_0.8_lossA/2025-03-27_11-30-31
          _90: 
            _8: 
        sampling:
          _None: 
            _8: 
      pc:
        pc:
          _5:
            _8: 
          _10:
            _8: pcmae_cifar10_pc_pc_pc_0.1_lossA/2025-04-18_22-55-20
          _20:
            _8: pcmae_cifar10_pc_pc_pc_0.2_lossA/2025-04-18_22-55-33
          _30:
            _8: pcmae_cifar10_pc_pc_pc_0.3_lossA/2025-04-18_22-55-33
          _40:
            _8: pcmae_cifar10_pc_pc_pc_0.4_lossA/2025-04-18_22-55-28
          _50:
            _8: pcmae_cifar10_pc_pc_pc_0.5_lossA/2025-04-18_22-55-28
        sampling_pc:
          _None: 
            _8: 
        sampling_rest_pc:
          _None:
            _8: 
    cifar10_kernel: 
      pc:
        pc:
          _5:
            _8: 
          _10:
            _8: 
          _20:
            _8:
          _30:
            _8:
          _40:
            _8:
          _50:
            _8: 
    bloodmnist:
      pixel:
        pixel:
          _50:
            _8: 
          _60:
            _8: mae_blood_pixel_0.6_lossA/2025-03-28_18-29-04 #mae_blood_pixel_0.6_lossA/2025-03-27_12-02-47
          _75:
            _8: 
            _16: 
          _80:
            _8:
          _90: 
            _8: mae_tiny_pixel_0.9_lossA/2025-03-28_18-29-04
        sampling:
          _None: 
            _8: 
      pc:
        pc:
          _5:
            _8: 
          _10:
            _8: 
          _20:
            _8: pcmae_tiny_pc_pc_pc_0.2_lossA/2025-03-26_23-23-30
          _30:
            _8: pcmae_blood_pc_pc_pc_0.3_lossA/2025-03-27_12-05-02
          _40:
            _8: 
          _50:
            _8: 
        sampling_pc:
          _None: 
            _8: 
    dermamnist:
      pixel:
        pixel:
          _50:
            _8: 
          _60:
            _8: 
          _75:
            _8: 
            _16: 
          _80:
            _8: 
          _90: 
            _8: mae_derma_pixel_0.9_lossA/2025-03-28_18-29-04 #mae_tiny_pixel_0.9_lossA/2025-03-28_18-29-04 #mae_derma_pixel_0.9_lossA/2025-03-27_12-06-34
        sampling:
          _None: 
            _8: 
      pc:
        pc:
          _5:
            _8: 
          _10:
            _8: 
          _20:
            _8: pcmae_tiny_pc_pc_pc_0.2_lossA/2025-03-26_23-23-30
          _30:
            _8: pcmae_derma_pc_pc_pc_0.3_lossA/2025-03-27_15-22-36
          _40:
            _8:
          _50:
            _8: 
        sampling_pc:
          _None:
            _8:
    pathmnist:
      pixel:
        pixel:
          _50:
            _8:
          _60:
            _8:
          _75:
            _8: 
            _16: 
          _80:
            _8: mae_path_pixel_0.8_lossA/2025-03-28_18-29-04
          _90: 
            _8: mae_tiny_pixel_0.9_lossA/2025-03-28_18-29-04
        sampling:
          _None: 
            _8: 
      pc:
        pc:
          _5:
            _8: 
          _10:
            _8: pcmae_path_pc_pc_pc_0.1_lossA/2025-03-27_11-54-31
          _20:
            _8: pcmae_tiny_pc_pc_pc_0.2_lossA/2025-03-26_23-23-30
          _30:
            _8: 
          _40:
            _8: 
          _50:
            _8: 
        sampling_pc:
          _None: 
            _8: 
  vit-b:
    imagenet:
      pixel:
        pixel:
          _75:
            _16: mae_imagenet_pixel_0.75_model_vit-b_lossA/2025-04-15_05-29-33/
      pc:
        pc:
          _30:
            _16: pcmae_imagenet_pc_pc_pc_0.3_model_vit-b_lossA/2025-03-23_00-11-05
          _40:
            _16: 
    tinyimagenet:
      pixel:
        pixel:
          _60:
            _8: mae_tiny_pixel_0.6_model_vit-b_lossA/2025-04-14_22-28-07
          _75:
            _8: mae_tiny_pixel_0.75_model_vit-b_lossA/2025-04-14_22-28-07 #mae_tiny_pixel_0.75_model_vit-b_lossA/2025-03-28_00-46-00 #mae_tiny_pixel_0.75_model_vit-b_lossA/2025-03-26_11-18-54
          _80:
            _8: mae_tiny_pixel_0.8_model_vit-b_lossA/2025-04-14_22-28-07
          _90:
            _8: mae_tiny_pixel_0.9_model_vit-b_lossA/2025-04-14_22-28-07
      pc:
        pc:
          _10:
            _8: pcmae_tiny_pc_pc_pc_0.1_model_vit-b_lossA/2025-03-26_13-35-49
          _20:
            _8: pcmae_tiny_pc_pc_pc_0.2_model_vit-b_lossA/2025-03-26_13-35-49
          _30:
            _8: pcmae_tiny_pc_pc_pc_0.3_model_vit-b_lossA/2025-03-26_13-37-05
          _40:
            _8: pcmae_tiny_pc_pc_pc_0.4_model_vit-b_lossA/2025-03-26_15-07-44
    cifar10: 
      pixel:
        pixel:
          _60:
            _8: 
          _80:
            _8: mae_cifar10_pixel_0.8_model_vit-b/2024-09-21_09-57-42
          _90:
            _8: 
          _95:
            _8:
          _75:
            _8: mae_cifar10_pixel_0.75_model_vit-b/2024-09-22_22-12-20
      pc:
        pc:
          _5:
            _8: pcmae_cifar10_pc_pc_pc_0.05_model_vit-b_lossA/2024-11-13_18-50-53
          _10:
            _8: pcmae_cifar10_pc_pc_pc_0.1_model_vit-b_lossA/2024-11-13_18-50-52
          _20:
            _8: pcmae_cifar10_pc_pc_pc_0.2_model_vit-b_lossA/2024-11-13_18-50-53
          _30:
            _8: pcmae_cifar10_pc_pc_pc_0.3_model_vit-b_lossA/2024-11-13_18-50-53
          _40: 
            _8: pcmae_cifar10_pc_pc_pc_0.4_model_vit-b_lossA/2024-11-13_18-50-53
          _50: 
            _8: pcmae_cifar10_pc_pc_pc_0.5_model_vit-b_lossA/2024-11-13_18-50-53
        sampling_pc:
          _None: 
            _8: pcmae_cifar10_pcsampling_model_vit-b_lossA/2024-11-16_04-50-56
        sampling_rest_pc:
          _None:
            _8: pcmae_cifar10_pcsampling_rest_model_vit-b_lossA/2024-11-17_19-51-40
    bloodmnist:
      pixel:
        pixel:
          _60:
            _8: mae_blood_pixel_0.6_model_vit-b/2024-09-21_09-57-41
          _75:
            _8: mae_blood_pixel_0.75_model_vit-b/2024-09-22_22-12-52
          _80:
            _8:
          _90:
            _8: 
          _95:
            _8: 
      pc:
        pc:
          _5:
            _8: pcmae_blood_pc_pc_pc_0.05_model_vit-b_lossA/2024-11-15_19-55-43
          _10:
            _8: pcmae_blood_pc_pc_pc_0.1_model_vit-b_lossA/2024-11-15_19-55-48
          _20:
            _8: pcmae_blood_pc_pc_pc_0.2_model_vit-b_lossA/2024-11-15_19-55-49
          _30:
            _8: pcmae_blood_pc_pc_pc_0.3_model_vit-b_lossA/2024-11-15_19-55-49
          _40:
            _8: pcmae_blood_pc_pc_pc_0.4_model_vit-b_lossA/2024-11-15_19-56-08
          _50:
            _8: pcmae_blood_pc_pc_pc_0.5_model_vit-b_lossA/2024-11-15_19-56-16
        sampling_pc:
          _None:
            _8: pcmae_blood_pcsampling_model_vit-b_lossA/2024-11-16_04-58-11
        sampling_rest_pc:
          _None:
            _8: pcmae_blood_pcsampling_rest_model_vit-b_lossA/2024-11-17_19-51-40
    dermamnist: 
      pixel:
        pixel:
          _60:
            _8: 
          _75:
            _8: mae_derma_pixel_0.75_model_vit-b/2024-09-22_22-12-23
          _80:
            _8: mae_derma_pixel_0.8_model_vit-b/2024-09-21_09-57-40
          _90:
            _8: 
          _95:
            _8: 
      pc:
        pc:
          _5:
            _8: pcmae_derma_pc_pc_pc_0.05_model_vit-b_lossA/2024-11-15_19-56-48
          _10:
            _8: pcmae_derma_pc_pc_pc_0.1_model_vit-b_lossA/2024-11-15_19-58-13
          _20:
            _8: pcmae_derma_pc_pc_pc_0.2_model_vit-b_lossA/2024-11-15_20-01-07
          _30:
            _8: pcmae_derma_pc_pc_pc_0.3_model_vit-b_lossA/2024-11-15_20-01-41
          _40:
            _8: pcmae_derma_pc_pc_pc_0.4_model_vit-b_lossA/2024-11-15_20-17-40
          _50:
            _8: pcmae_derma_pc_pc_pc_0.5_model_vit-b_lossA/2024-11-15_22-29-10
        sampling_pc:
          _None:
            _8: pcmae_derma_pcsampling_model_vit-b_lossA/2024-11-16_05-03-23
        sampling_rest_pc:
          _None:
            _8: pcmae_derma_pcsampling_rest_model_vit-b_lossA/2024-11-17_19-52-36
    pathmnist:
      pixel:
        pixel:
          _60:
            _8: 
          _75:
            _8:
          _80:
            _8: mae_path_pixel_0.8_model_vit-b/2024-09-21_09-57-41
          _90:
            _8:
          _95:
            _8:
      pc:
        pc: 
          _5: 
            _8: pcmae_path_pc_pc_pc_0.05_model_vit-b_lossA/2024-11-15_22-32-16
          _10: 
            _8: pcmae_path_pc_pc_pc_0.1_model_vit-b_lossA/2024-11-15_22-36-51
          _20:
            _8: pcmae_path_pc_pc_pc_0.2_model_vit-b_lossA/2024-11-15_22-37-24
          _30:
            _8: pcmae_path_pc_pc_pc_0.3_model_vit-b_lossA/2024-11-15_22-37-39
          _40:
            _8: pcmae_path_pc_pc_pc_0.4_model_vit-b_lossA/2024-11-15_22-42-3
          _50:
            _8: pcmae_path_pc_pc_pc_0.5_model_vit-b_lossA/2024-11-16_01-18-09
        sampling_pc:
          _None: 
            _8: pcmae_path_pcsampling_model_vit-b_lossA/2024-11-16_04-59-17
        sampling_rest_pc:
          _None:
            _8: pcmae_path_pcsampling_rest_model_vit-b_lossA/2024-11-17_19-52-36
