# @package _global_

base_logs_home: /cluster/project/sachan/callen/mae_alice
base_data_home: /cluster/project/sachan/callen/data_alice

checkpoint_folders:
  tinyimagenet:
    pixel:
      pixel:
        _50:
          _8: mae_tiny_pc_0.0_pixel_0.5/2024-08-27_19-14-37
        _60:
          _8: mae_tiny_pc_0.0_pixel_0.6/2024-08-27_19-14-37
        _75:
          _8: mae_tiny_pc_0.0_pixel_0.75/2024-08-27_19-14-36
          _16: mae_tiny_pc_0.0_pixel_0.75_patch_16/2024-08-29_11-42-12
        _80:
          _8: mae_tiny_pc_0.0_pixel_0.8/2024-08-27_19-14-36
        _90: 
          _8: mae_tiny_pc_0.0_pixel_0.9/2024-08-27_19-14-36
      sampling:
        _None: 
          _8: mae_sampling_tiny_pc_0.0_pixel_0.0/2024-09-15_17-49-29
    pc:
      bvt:
        _60: 
          _8: pcmae_tiny_bvt_pc_tvb_0.6_pixel_0.0/2024-09-02_21-08-48
        _70:
          _8: pcmae_tiny_bvt_pc_tvb_0.7_pixel_0.0/2024-09-02_21-08-48
        _80: 
          _8: pcmae_tiny_bvt_pc_tvb_0.8_pixel_0.0/2024-09-02_21-08-48
        _85: 
          _8: 
        _90:
          _8: pcmae_tiny_bvt_pc_tvb_0.9_pixel_0.0/2024-09-02_21-26-18
      tvb:
        _60:
          _8: 
        _70:
          _8: pcmae_tiny_tvb_pc_tvb_0.7_pixel_0.0/2024-09-02_18-17-06
        _80: 
          _8: pcmae_tiny_tvb_pc_tvb_0.8_pixel_0.0/2024-09-02_18-17-06
        _85: 
          _8: pcmae_tiny_tvb_pc_tvb_0.85_pixel_0.0/2024-09-02_18-17-06
        _90:
          _8: 
      sampling_pc:
        _None: 
          _8: pcmae_tiny_pcsampling_pc_0.0_pixel_0.0/2024-09-15_09-00-49
      sampling_ratio:
        _None: 
          _8: pcmae_tiny_ratiosampling_pc_0.0_pixel_0.0/2024-09-15_09-00-49
  cifar10: 
    pixel:
      pixel:
        _50:
          _8: mae_cifar10_pc_0.0_pixel_0.5/2024-08-27_19-14-36
        _60:
          _8: mae_cifar10_pc_0.0_pixel_0.6/2024-08-27_19-14-36
        _75:
          _8: mae_cifar10_pc_0.0_pixel_0.75/2024-08-27_19-14-37
          _16: mae_cifar10_pc_0.0_pixel_0.75_patch_16/2024-08-30_14-23-57
        _80:
          _8: mae_cifar10_pc_0.0_pixel_0.8/2024-08-27_19-14-37
        _90: 
          _8: mae_cifar10_pc_0.0_pixel_0.9/2024-08-27_19-14-37
      sampling:
        _None: 
          _8: mae_sampling_cifar10_pc_0.0_pixel_0.0/2024-09-15_17-50-13
    pc:
      tvb:
        _60: 
          _8: pcmae_cifar10_tvb_pc_tvb_0.6_pixel_0.0/2024-09-02_18-37-50
        _70:
          _8: pcmae_cifar10_tvb_pc_tvb_0.7_pixel_0.0/2024-09-02_18-37-50
        _80: 
          _8: pcmae_cifar10_tvb_pc_tvb_0.8_pixel_0.0/2024-09-02_19-42-01
        _85: 
          _8: pcmae_cifar10_tvb_pc_tvb_0.85_pixel_0.0/2024-09-02_19-42-26
        _90:
          _8: pcmae_cifar10_tvb_pc_tvb_0.9_pixel_0.0/2024-09-02_19-42-26
      bvt:
        _60:
          _8: pcmae_cifar10_bvt_pc_tvb_0.6_pixel_0.0/2024-09-02_21-54-02
        _70:
          _8: pcmae_cifar10_bvt_pc_tvb_0.7_pixel_0.0/2024-09-02_21-54-02
        _80: 
          _8: pcmae_cifar10_bvt_pc_tvb_0.8_pixel_0.0/2024-09-02_22-00-51
        _85: 
          _8: pcmae_cifar10_bvt_pc_tvb_0.85_pixel_0.0/2024-09-02_22-01-58
        _90:
          _8: pcmae_cifar10_bvt_pc_tvb_0.9_pixel_0.0/2024-09-02_22-07-00
      sampling_pc:
        _None: 
          _8: pcmae_cifar10_pcsampling_pc_0.0_pixel_0.0/2024-09-10_21-43-36
      sampling_ratio:
        _None: 
          _8: pcmae_cifar10_ratiosampling_pc_0.0_pixel_0.0/2024-09-08_16-03-37
  bloodmnist:
    pixel:
      pixel:
        _50:
          _8: mae_blood_pc_0.0_pixel_0.5/2024-08-27_19-14-36
        _60:
          _8: mae_blood_pc_0.0_pixel_0.6/2024-08-27_19-14-36
        _75:
          _8: mae_blood_pc_0.0_pixel_0.75/2024-08-27_19-14-36
          _16: mae_blood_pc_0.0_pixel_0.75_patch_16/2024-08-29_11-42-12
        _80:
          _8: mae_blood_pc_0.0_pixel_0.8/2024-08-27_19-14-38
        _90: 
          _8: mae_blood_pc_0.0_pixel_0.9/2024-08-27_19-14-49
      sampling:
        _None:
          _8: mae_sampling_blood_pc_0.0_pixel_0.0/2024-09-15_17-49-36
    pc:
      tvb:
        _60: 
          _8: pcmae_blood_tvb_pc_tvb_0.6_pixel_0.0/2024-09-02_19-53-13
        _70:
          _8: pcmae_blood_tvb_pc_tvb_0.7_pixel_0.0/2024-09-02_19-53-13
        _80: 
          _8: pcmae_blood_tvb_pc_tvb_0.8_pixel_0.0/2024-09-02_19-58-20
        _85: 
          _8: pcmae_blood_tvb_pc_tvb_0.85_pixel_0.0/2024-09-02_19-58-20
        _90:
          _8: pcmae_blood_tvb_pc_tvb_0.9_pixel_0.0/2024-09-02_20-25-35
      bvt:
        _60:
          _8: pcmae_blood_bvt_pc_tvb_0.6_pixel_0.0/2024-09-02_22-12-57
        _70:
          _8: pcmae_blood_bvt_pc_tvb_0.7_pixel_0.0/2024-09-02_22-14-57
        _80: 
          _8: pcmae_blood_bvt_pc_tvb_0.8_pixel_0.0/2024-09-02_22-30-04
        _85: 
          _8: pcmae_blood_bvt_pc_tvb_0.85_pixel_0.0/2024-09-02_22-32-02
        _90:
          _8: pcmae_blood_bvt_pc_tvb_0.9_pixel_0.0/2024-09-02_22-35-49
      sampling_pc:
        _None: 
          _8: pcmae_blood_pcsampling_pc_0.0_pixel_0.0/2024-09-08_16-03-37
      sampling_ratio:
        _None: 
          _8: pcmae_blood_ratiosampling_pc_0.0_pixel_0.0/2024-09-08_16-03-46
  dermamnist: 
    pixel:
      pixel:
        _50:
          _8: mae_derma_pc_0.0_pixel_0.5/2024-08-27_19-15-15
        _60:
          _8: mae_derma_pc_0.0_pixel_0.6/2024-08-27_19-15-15
        _75:
          _8: mae_derma_pc_0.0_pixel_0.75/2024-08-27_19-14-57
          _16: mae_derma_pc_0.0_pixel_0.75_patch_16/2024-08-29_11-42-12
        _80:
          _8: mae_derma_pc_0.0_pixel_0.8/2024-08-27_19-14-57
        _90: 
          _8: mae_derma_pc_0.0_pixel_0.9/2024-08-27_19-14-55
      sampling:
        _None: 
          _8: mae_sampling_derma_pc_0.0_pixel_0.0/2024-09-15_17-49-36
    pc:
      bvt:
        _60: 
          _8: pcmae_derma_bvt_pc_tvb_0.6_pixel_0.0/2024-09-02_23-48-15
        _70:
          _8: pcmae_derma_bvt_pc_tvb_0.7_pixel_0.0/2024-09-02_23-48-45
        _80: 
          _8: pcmae_derma_bvt_pc_tvb_0.8_pixel_0.0/2024-09-02_23-49-49
        _85: 
          _8: pcmae_derma_bvt_pc_tvb_0.85_pixel_0.0/2024-09-02_23-50-31
        _90:
          _8: pcmae_derma_bvt_pc_tvb_0.9_pixel_0.0/2024-09-03_00-31-01
      tvb:
        _60:
          _8: pcmae_derma_tvb_pc_tvb_0.6_pixel_0.0/2024-09-02_21-08-48
        _70:
          _8: pcmae_derma_tvb_pc_tvb_0.7_pixel_0.0/2024-09-02_21-08-48
        _80: 
          _8: pcmae_derma_tvb_pc_tvb_0.8_pixel_0.0/2024-09-02_21-08-48
        _85: 
          _8: pcmae_derma_tvb_pc_tvb_0.85_pixel_0.0/2024-09-02_21-08-48
        _90:
          _8: pcmae_derma_tvb_pc_tvb_0.9_pixel_0.0/2024-09-02_21-08-48
      sampling_pc:
        _None:
          _8: pcmae_derma_pcsampling_pc_0.0_pixel_0.0/2024-09-13_11-27-24
      sampling_ratio:
        _None:
          _8: pcmae_derma_ratiosampling_pc_0.0_pixel_0.0/2024-09-13_11-27-24
  pathmnist:
    pixel:
      pixel:
        _50:
          _8: mae_path_pc_0.0_pixel_0.5/2024-08-27_19-14-49
        _60:
          _8: mae_path_pc_0.0_pixel_0.6/2024-08-27_19-15-43
        _75:
          _8: mae_path_pc_0.0_pixel_0.75/2024-08-27_19-15-43
          _16: mae_path_pc_0.0_pixel_0.75_patch_16/2024-08-29_11-42-12
        _80:
          _8: mae_path_pc_0.0_pixel_0.8/2024-08-27_19-15-43
        _90: 
          _8: mae_path_pc_0.0_pixel_0.9/2024-08-27_19-15-15
      sampling:
        _None: 
          _8: mae_sampling_path_pc_0.0_pixel_0.0/2024-09-15_17-49-36
    pc:
      tvb:
        _60: 
          _8: pcmae_path_tvb_pc_tvb_0.6_pixel_0.0/2024-09-02_20-50-51
        _70:
          _8: 
        _80: 
          _8: pcmae_path_tvb_pc_tvb_0.8_pixel_0.0/2024-09-02_20-55-19
        _85: 
          _8: pcmae_path_tvb_pc_tvb_0.85_pixel_0.0/2024-09-02_20-55-19
        _90:
          _8: pcmae_path_tvb_pc_tvb_0.9_pixel_0.0/2024-09-02_20-55-19
      bvt:
        _60:
          _8: pcmae_path_bvt_pc_tvb_0.6_pixel_0.0/2024-09-02_23-11-04
        _70:
          _8: pcmae_path_bvt_pc_tvb_0.7_pixel_0.0/2024-09-02_23-14-03
        _80: 
          _8: pcmae_path_bvt_pc_tvb_0.8_pixel_0.0/2024-09-02_23-27-17
        _85: 
          _8: pcmae_path_bvt_pc_tvb_0.85_pixel_0.0/2024-09-02_23-28-10
        _90:
          _8: pcmae_path_bvt_pc_tvb_0.9_pixel_0.0/2024-09-02_23-47-42
      sampling_pc:
        _None: 
          _8: pcmae_path_pcsampling_pc_0.0_pixel_0.0/2024-09-15_09-00-49
      sampling_ratio:
        _None: 
          _8: pcmae_path_ratiosampling_pc_0.0_pixel_0.0/2024-09-13_11-27-24