# @package _global_

base_logs_home: /cluster/project/sachan/callen/mae_alice
base_data_home: /cluster/project/sachan/callen/data_alice

checkpoint_folders:
  tinyimagenet:
    pixel:
      _50:
        _8: mae_tiny_pc_0.0_pixel_0.5/2024-08-27_19-14-37
      _60:
        _8: mae_tiny_pc_0.0_pixel_0.6/2024-08-27_19-14-37
      _75:
        _8: mae_tiny_pc_0.0_pixel_0.75/2024-08-27_19-14-36
        _16: mae_tiny_pc_0.0_pixel_0.75_patch_16/2024-08-29_11-42-12
      _80:
        _8: mae_tiny_pc_0.0_pixel_0.8/2024-08-27_19-14-36
      _90: 
        _8: mae_tiny_pc_0.0_pixel_0.9/2024-08-27_19-14-36
  cifar10: {}
  bloodmnist: {}
  dermamnist: {}
  pathmnist: {}