# @package _global_

base_logs_home: /logs
base_data_home: /data


checkpoint_folders:
  vit-t:
    cifar10:
      pc:
        pc:
          _80:
            _8: /mypath_logs_folder
        pc_sampling:
          _None: 
            _8: /mypath_logs_folder
