# @package _global_

masking:
  type: segmentation
  strategy: random
  pixel_ratio: 0.0
  pc_ratio: 0.0
  ratio:  ${decimal_2_percent:${masking.pixel_ratio}}
  str_ratio: ${convert_str:${masking.ratio}}

