# @package _global_

masking:
  type: segmentation
  strategy: partial # leave at least one patch per object
  pixel_ratio: 0.75
  pc_ratio: 0.0
  ratio:  ${decimal_2_percent:${masking.pixel_ratio}}
  str_ratio: ${convert_str:${masking.ratio}}

