# @package _global_

data:
  name: bloodmnist
  resolution: 64
  channels: 3
  patch_size: 8
  str_patch_size: ${convert_str:${data.patch_size}}
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
  classes: 8

datasets:
  train:
    _target_: medmnist.BloodMNIST
    root: ${base_data_home}/medmnist
    split: train
    download: ${download}
    size: ${data.resolution}
    transform: ${transformation.train}

  val:
    _target_: medmnist.BloodMNIST
    root: ${base_data_home}/medmnist
    split: val
    download: ${download}
    size: ${data.resolution}
    transform: ${transformation.train}

  test:
    _target_: medmnist.BloodMNIST
    root: ${base_data_home}/medmnist
    split: val
    download: ${download}
    size: ${data.resolution}
    transform: ${transformation.train}

datamodule: 
  _target_: dataset.dataloader.DataModule
  batch_size: 512
  num_workers: 8
  classes: ${data.classes}
  channels: ${data.channels}
  resolution: ${data.resolution}

datamodule_eval:
  _target_: dataset.dataloader.DataModule
  batch_size: 512
  num_workers: ${datamodule.num_workers}
  classes: ${data.classes}
  channels: ${data.channels}
  resolution: ${data.resolution}