# @package _global_

data:
  name: cifar10
  resolution: 32
  channels: 3
  patch_size: 8
  str_patch_size:  ${convert_str:${data.patch_size}}
  mean: [0.4914, 0.4822, 0.4465]
  std: [0.247, 0.243, 0.261]
  classes: 10

datasets:
  train:
    _target_: torchvision.datasets.CIFAR10
    root: ${base_data_home}/
    train: True
    download: ${download}
    transform: ${transformation.train}

  val:
    _target_: torchvision.datasets.CIFAR10
    root: ${base_data_home}/
    train: False
    download: ${download}
    transform: ${transformation.val}

  test:
    _target_: torchvision.datasets.CIFAR10
    root: ${base_data_home}/
    train: False
    download: ${download}
    transform: ${transformation.val}

datamodule: 
  _target_: dataset.dataloader.DataModule
  batch_size: 512
  num_workers: 8
  classes: ${data.classes}
  channels: ${data.channels}
  resolution: ${data.resolution}

datamodule_eval:
  _target_: dataset.dataloader.DataModule
  batch_size: 512
  num_workers: ${datamodule.num_workers}
  classes: ${data.classes}
  channels: ${data.channels}
  resolution: ${data.resolution}