# @package _global_

data:
  name: clevr
  resolution: 224
  height: 240
  width: 320
  channels: 3
  batch_size: 128
  patch_size: 16
  eval_fn: 
    _target_: torch.nn.BCEWithLogitsLoss
    reduction: mean
  eval_logit_fn:
    _target_: torch.nn.Sigmoid
    _: 
  eval_type: multilabel
  str_patch_size:  ${convert_str:${data.patch_size}}
  mean: 
    _target_: torch.tensor
    data: 
      _target_: numpy.load
      file: 
  std: 
    _target_: torch.tensor
    data: 
      _target_: numpy.load
      file: 
  classes: 24

datasets:
  train:
    _target_: dataset.CLEVRCustomDataset.CLEVRCustomDataset
    root: ${base_data_home}
    # transform: ${transformation.train}
    transform: None
    split: "train"
    morph: "none"
    load_masks: True
    #transform: ${transformation.train}

  val:
    _target_: dataset.CLEVRCustomDataset.CLEVRCustomDataset
    root: ${base_data_home}
    # transform: ${transformation.val}
    transform: None
    split: "val"
    morph: "none"
    load_masks: True

  test:
    _target_: dataset.CLEVRCustomDataset.CLEVRCustomDataset
    root: ${base_data_home}
    # transform: ${transformation.val}
    transform: None
    split: "test"
    morph: "none"
    load_masks: True
    # transform: ${transformation.val}

datamodule: 
  _target_: dataset.dataloader.DataModule
  batch_size: ${data.batch_size}
  num_workers: 8
  classes: ${data.classes}
  channels: ${data.channels}
  resolution:
    - ${data.height}
    - ${data.width}

datamodule_eval:
  _target_: dataset.dataloader.DataModule
  batch_size: ${data.batch_size}
  num_workers: ${datamodule.num_workers}
  classes: ${data.classes}
  channels: ${data.channels}
  resolution:
    - ${data.height}
    - ${data.width}

extradata:
  # TODO: Set correct paths for pca extradata
  pcamodule:
    _target_ : numpy.load
    file: ${base_data_home}/cifar-10-batches-py/pc_matrix.npy
    # file: ""

  eigenratiomodule:
    _target_: numpy.load
    file: ${base_data_home}/cifar-10-batches-py/pc_matrix.npy
    # file: ""

  pmae_random_resized_cropping: false
